  espruinohub:
    container_name: espruinohub
    image: humbertosales/espruinohub-docker-rpi
    network_mode: host
    privileged: true
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"
