  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=%randomAdminPassword%
      - MYSQL_DATABASE=default
      - MYSQL_USER=mariadbuser
      - MYSQL_PASSWORD=%randomPassword%
    volumes:
      - ./volumes/mariadb/config:/config
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - iotstack_nw
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"

