  python:
    container_name: python
    build: ./services/python/.
    restart: unless-stopped
    network_mode: host
    # networks:
    #   - hosts_nw
    volumes:
      - ./volumes/python/app:/usr/src/app
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"
